AirportRoute = {
    Name = 'airport_route',
    SpawnPoint = {x = -923.7001, y = -2283.8886, z = 6.7090, heading = 333.65},
    -- RouteLines: cada linha tem BusModel, BusColor, Doors e lista de paragens
    RouteLines = {
        {
            BusModel = 'bus',
            BusColor = 5,
            Doors = {2, 3},
            FirstSeat = 1,
            {
                Name = 'stop_banner_hotel',
                Coords = {x = -1664.8002, y = -538.1304, z = 35.2513},
                Type = 'BusStop',
                Doors = {2, 3},
                MinFare = 5,
                MaxFare = 15,
                UnloadType = UnloadType.None,
            },
            {
                Name = 'stop_airport',
                Coords = {x = -1031.2937, y = -2729.3339, z = 13.7566},
                Type = 'BusStop',
                Doors = {2, 3},
                MinFare = 5,
                MaxFare = 20,
                UnloadType = UnloadType.All,
            },
            {
                Name = 'stop_elgin',
                Coords = {x = -1304.3708, y = -407.5448, z = 35.5009},
                Type = 'BusStop',
                Doors = {2, 3},
                MinFare = 5,
                MaxFare = 15,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_venetian',
                Coords = {x = -1333.0507, y = -1089.8925, z = 6.9793},
                Type = 'BusStop',
                Doors = {2, 3},
                MinFare = 5,
                MaxFare = 15,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_airport',
                Coords = {x = -1031.2937, y = -2729.3339, z = 13.7566},
                Type = 'BusStop',
                Doors = {2, 3},
                MinFare = 5,
                MaxFare = 20,
                UnloadType = UnloadType.All,
            },
            {
                Name = 'stop_viceroy',
                Coords = {x = -824.8701, y = -1221.3138, z = 7.3654},
                Type = 'BusStop',
                Doors = {2, 3},
                MinFare = 5,
                MaxFare = 15,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_crastenburg',
                Coords = {x = -880.8395, y = -2110.7658, z = 9.0868},
                Type = 'BusStop',
                Doors = {2, 3},
                MinFare = 5,
                MaxFare = 15,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_opium_nights',
                Coords = {x = -695.0627, y = -2283.1557, z = 13.0476},
                Type = 'BusStop',
                Doors = {2, 3},
                MinFare = 5,
                MaxFare = 15,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_airport',
                Coords = {x = -1031.2937, y = -2729.3339, z = 13.7566},
                Type = 'BusStop',
                Doors = {2, 3},
                MinFare = 5,
                MaxFare = 20,
                UnloadType = UnloadType.All,
            },
        }
    }
}