ScenicRoute = {
    Name = 'scenic_route',
    SpawnPoint = {x = 427.6807, y = -582.7913, z = 28.5165, heading = 135.64},
    RouteLines = {
        {
            BusModel = 'coach',
            BusColor = 333,
            Doors = {0},
            FirstSeat = 1,
            {
                Name = 'stop_dashound',
                Coords = {x = 424.7632, y = -638.9176, z = 28.5001},
                Type = 'BusStop',
                Doors = {0},
                MinFare = 20,
                MaxFare = 50,
                UnloadType = UnloadType.All,
            },
            {
                Name = 'stop_banham_canyon',
                Coords = {x = -2973.2265, y = 408.1283, z = 15.1100},
                Type = 'BusStop',
                Doors = {0},
                MinFare = 20,
                MaxFare = 50,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_lago_zancudo',
                Coords = {x = -2522.2990, y = 2340.5200, z = 33.0598},
                Type = 'BusStop',
                Doors = {0},
                MinFare = 20,
                MaxFare = 50,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_north_chumash',
                Coords = {x = -2200.12, y = 4258.054, z = 47.7155},
                Type = 'BusStop',
                Doors = {0},
                MinFare = 20,
                MaxFare = 50,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_chiliad',
                Coords = {x = -1525.0812, y = 4949.1962, z = 61.9035},
                Type = 'BusStop',
                Doors = {0},
                MinFare = 20,
                MaxFare = 50,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_paleto_bay',
                Coords = {x = -329.8910, y = 6185.0571, z = 31.6218},
                Type = 'BusStop',
                Doors = {0},
                MinFare = 20,
                MaxFare = 50,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_grapeseed',
                Coords = {x = 1660.6237, y = 4857.0190, z = 41.2123},
                Type = 'BusStop',
                Doors = {0},
                MinFare = 20,
                MaxFare = 50,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_sandy_shores',
                Coords = {x = 1958.85, y = 3768.2802, z = 32.2184},
                Type = 'BusStop',
                Doors = {0},
                MinFare = 20,
                MaxFare = 50,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_senora_park',
                Coords = {x = 2237.2424, y = 3190.7673, z = 48.7102},
                Type = 'BusStop',
                Doors = {0},
                MinFare = 20,
                MaxFare = 50,
                UnloadType = UnloadType.Some,
            },
            {
                Name = 'stop_harmony',
                Coords = {x = 549.9940, y = 2700.2866, z = 42.1508},
                Type = 'BusStop',
                Doors = {0},
                MinFare = 20,
                MaxFare = 50,
                UnloadType = UnloadType.All,
            },
        }
    }
}