SDC = {}

SDC.Framework = "esx"

SDC.DetectorCooldown = 2
SDC.MaxSoundDistance = 20
SDC.DetectorSoundFile = "detectorbeep" 
SDC.DetectorProps = { 
    "ch_prop_ch_metal_detector_01a",
}
SDC.SpawnDetectors = { 
   -- {Coords = vector4(-1133.31, -2806.17, 27.708, 334.72), Model = "ch_prop_ch_metal_detector_01a"},
}
SDC.SpawnDetectorDist = 50 
SDC.RemoveAllOfBlastedItem = false

SDC.BlacklistedItems = {
    'weapon_dagger',
	'weapon_crowbar',
	'weapon_flashlight',
	'weapon_golfclub',
	'weapon_hammer',
	'weapon_hatchet',
	'weapon_knuckle',
	'weapon_knife',
	'weapon_machete',
	'weapon_switchblade',
	'weapon_wrench',
	'weapon_battleaxe',
	'weapon_handcuffs',
	'weapon_pistol',
	'weapon_pistol_mk2',
	'weapon_combatpistol',
	'weapon_appistol',
	'weapon_stungun',
	'weapon_pistol50',
	'weapon_snspistol',
	'weapon_heavypistol',
	'weapon_vintagepistol',
	'weapon_flaregun',
	'weapon_marksmanpistol',
	'weapon_revolver',
	'weapon_revolver_mk2',
	'weapon_doubleaction',
	'weapon_snspistol_mk2',
	'weapon_raypistol',
	'weapon_navyrevolver',
	'weapon_gadgetpistol',
	'weapon_microsmg',
	'weapon_smg',
	'weapon_smg_mk2',
	'weapon_assaultsmg',
	'weapon_combatpdw',
	'weapon_machinepistol',
	'weapon_minismg',
	'weapon_raycarbine',
	'weapon_pumpshotgun',
	'weapon_sawnoffshotgun',
	'weapon_assaultshotgun',
	'weapon_bullpupshotgun',
	'weapon_musket',
	'weapon_heavyshotgun',
	'weapon_dbshotgun',
	'weapon_autoshotgun',
	'weapon_combatshotgun',
	'weapon_pumpshotgun_mk2',
	'weapon_assaultrifle',
	'weapon_assaultrifle_mk2',
	'weapon_carbinerifle',
	'weapon_carbinerifle_mk2',
	'weapon_advancedrifle',
	'weapon_specialcarbine',
	'weapon_bullpuprifle',
	'weapon_compactrifle',
	'weapon_specialcarbine_mk2',
	'weapon_bullpuprifle_mk2',
	'weapon_militaryrifle',
	'weapon_mg',
	'weapon_combatmg',
	'weapon_gusenberg',
	'weapon_combatmg_mk2',
	'weapon_sniperrifle',
	'weapon_heavysniper',
	'weapon_marksmanrifle',
	'weapon_remotesniper',
	'weapon_heavysniper_mk2',
	'weapon_marksmanrifle_mk2',
	'weapon_rpg',
	'weapon_grenadelauncher_smoke',
	'weapon_grenadelauncher',
	'weapon_minigun',
	'weapon_firework',
	'weapon_railgun',
	'weapon_hominglauncher',
	'weapon_compactlauncher',
	'weapon_rayminigun',
	'weapon_grenade',
	'weapon_bzgas',
	'weapon_proxmine',
	'weapon_pipebomb',
	'weapon_smokegrenade',
	'weapon_flare',
	'weapon_fireextinguisher',
    'weapon_airsoftm4'
}