Config = []

Config.HeaderDisabledApps = [
    "bank", 
    "whatsapp", 
    "meos", 
    "garage",
    "crypto",
    "racing",
    "houses",
    "lawyers",
    "trucker",
    "calculator",
    "twitter",
    "camera",
    "gallery",
    "snake",
    "pacman",
]

Config.DefaultCryptoPage = "general";

var PhoneApplications = {
    ["phone"]: {
        app: "phone",
        img: "phone.png",
        tooltipText: "Telefone",
        tooltipPos: "top",
        job: false,
        blockedjobs: {},
        slot: 1,
        Alerts: 0,
    },
    ["whatsapp"]: {
        app: "whatsapp",
        color: "#25d366",
        img: "whatsapp.png",
        icon: "fab fa-whatsapp",
        tooltipText: "Mensagens",
        tooltipPos: "top",
        style: "font-size: 2.8vh",
        job: false,
        blockedjobs: {},
        slot: 2,
        Alerts: 0,
    },
    ["settings"]: {
        app: "settings",
        color: "#636e72",
        img: "settings.png",
        icon: "fa fa-cog",
        tooltipText: "Definições",
        tooltipPos: "top",
        style: "padding-right: .08vh; font-size: 2.3vh",
        job: false,
        blockedjobs: {},
        slot: 3,
        Alerts: 0,
    },
    ["twitter"]: {
        app: "twitter",
        color: "#1da1f2",
        img: "twitter.png",
        icon: "fab fa-twitter",
        tooltipText: "Pwitter",
        tooltipPos: "top",
        job: false,
        blockedjobs: {},
        slot: 4,
        Alerts: 0,
    },
    ["mail"]: {
        app: "mail",
        color: "#00aeff",
        img: "mail.png",
        icon: "fas fa-envelope",
        style: "font-size: 2.8vh",
        tooltipText: "Mail",
        job: false,
        blockedjobs: {},
        slot: 16,
        Alerts: 0,
    },
    ["advert"]: {
        app: "advert",
        color: "radial-gradient(circle, rgba(255,214,0,1) 0%, rgba(255,132,0,1) 100%)",
        icon: "fas fa-ad",
        tooltipText: "Anúncios",
        job: false,
        blockedjobs: {},
        slot: 6,
        Alerts: 0,
    },
    ["bank"]: {
        app: "bank",
        color: "radial-gradient(circle, rgba(228,159,255,1) 0%, rgba(100,70,252,1) 100%)",
        //img: "banksign.png",
        icon: "fas fa-university",
        tooltipText: "Banco",
        job: false,
        blockedjobs: {},
        slot: 7,
        Alerts: 0,
    },
    ["racing"]: {
        app: "racing",
        color: "#19e8ff",
        img: "racing.png",
        icon: "fas fa-flag-checkered",
        tooltipText: "Corridas",
        job: false,
        blockedjobs: {},
        slot: 9,
        Alerts: 0,
    },
    ["lawyers"]: {
        app: "lawyers",
        color: "#353b48",
        img: "business.png",
        icon: "fas fa-user-tie",
        tooltipText: "Serviços",
        job: false,
        blockedjobs: {},
        slot: 5,
        Alerts: 0,
    },
    ["tinder"]: {
        app: "tinder",
        color: "#ff002b",
        img: "tinder.png",
        icon: "fas fa-fire",
        tooltipText: "Dates",
        job: false,
        blockedjobs: {},
        slot: 10,
        Alerts: 0,
    },
    ["camera"]: {
        app: "camera",
        color: "#696969",
        img: "camera.png",
        icon: "fas fa-camera",
        tooltipText: "Câmara",
        job: false,
        blockedjobs: {},
        slot: 8,
        Alerts: 0,
    },
    /*["instagram"]: {
        app: "instagram",
        color: "#eb302d",
        img: "instagram.png",
        icon: "fab fa-instagram",
        style: "font-size: 3.6vh",
        tooltipText: "Instagram",
        job: false,
        blockedjobs: {},
        slot: 17,
        Alerts: 0,
    },*/
    ["snake"]: {
        app: "snake",
        color: "radial-gradient(circle, rgba(190,255,234,1) 0%, rgba(35,255,0,1) 100%)",
        icon: "fas fa-dragon",
        tooltipText: "Snake",
        job: false,
        blockedjobs: {},
        slot: 15,
        Alerts: 0,
    },
    ["notes"]: {
        app: "notes",
        color: "#9452ff",
        img: "notes.png",
        icon: "fas fa-dragon",
        tooltipText: "Notas",
        job: false,
        blockedjobs: {},
        slot: 14,
        Alerts: 0,
    },
    ["darkweb"]: {
        app: "darkweb",
        color: "radial-gradient(circle, rgba(52,52,52,1) 0%, rgba(0,0,0,1) 100%)",
        //img: "darkweb.png",
        icon: "fas fa-skull-crossbones",
        tooltipText: "Dark-Web",
        job: false,
        blockedjobs: {},
        slot: 11,
        Alerts: 0,
    },
    ["calculator"]: {
        app: "calculator",
        color: "#ff9100",
        img: "calculator.png",
        icon: "fas fa-calculator",
        tooltipText: "Calculadora",
        job: false,
        blockedjobs: {},
        slot: 12,
        Alerts: 0,
    },
    ["gallery"]: {
        app: "gallery",
        color: "#b494ff",
        img: "gallery.png",
        icon: "fa-solid fa-images",
        tooltipText: "Galeria",
        job: false,
        blockedjobs: {},
        slot: 13,
        Alerts: 0,
    },
    ["flappybird"]: {
        app: "flappybird",
        icon: "fas fa-wave-square",
        img: "flappy.png",
        color: "radial-gradient(circle, rgb(101, 103, 102) 0%, rgba(0, 255, 64, 0.88) 100%)",
        tooltipText: "FlappyBird",
        job: false,
        blockedjobs: {},
        slot: 17,
        Alerts: 0,
    },
    /*["pacman"]: {
        app: "pacman",
        img: "pacman.png",
        color: "#b494ff",
        icon: "fas fa-dragon",
        tooltipText: "Pac-Man",
        job: false,
        blockedjobs: {},
        slot: 17,
        Alerts: 0,
    },*/
}